name: mental_health_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_gauges: ^20.2.47
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  table_calendar: ^3.0.1
  flutter_spinkit: ^5.1.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/Logo1.png
    - assets/facebook.png
    - assets/google.png
    - assets/apple.png
    - assets/mindy.png
    - assets/coach.png
