name: mental_health_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  fl_chart: ^0.70.1
  table_calendar: ^3.1.3
  syncfusion_flutter_gauges: ^20.3.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/Logo.png
     - assets/Logo1.png
     - assets/google.png
     - assets/facebook.png
     - assets/apple.png
     - assets/coach.png
     - assets/mindy.png