// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkkex4tiE3krB8eFBTGxiLZb53Jth3nM',
    appId: '1:876829031480:web:c5db00b0d018500d493acd',
    messagingSenderId: '876829031480',
    projectId: 'healthcare-7b637',
    authDomain: 'healthcare-7b637.firebaseapp.com',
    storageBucket: 'healthcare-7b637.firebasestorage.app',
    measurementId: 'G-P0B9KQCG8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7CwiP8mlBdM01BMc16IN-lj1GDTiuXbI',
    appId: '1:876829031480:android:7693d3d1f07d30cf493acd',
    messagingSenderId: '876829031480',
    projectId: 'healthcare-7b637',
    storageBucket: 'healthcare-7b637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Palukgw0hdcFS8XicAbs0kCrI_8lfx8',
    appId: '1:876829031480:ios:f5450652bdbb8c03493acd',
    messagingSenderId: '876829031480',
    projectId: 'healthcare-7b637',
    storageBucket: 'healthcare-7b637.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthCare',
  );
}
